spring:
  config:
    activate:
      on-profile: "qa"

app:
  details:
    name: loans-service
    author: Manjunath
    description: Loans Application
    version: "2.0.0"
    environment: "QA"

loans:
  message: "Welcome to Loans service"
  contactDetails:
    name: "Prakash"
    email: "paraguprakash99@gmail.com"
  onCallSupport:
    - (001)333-7689
    - (001)333-9876
