name: banking-services
services:
  accounts:
    image: "manjunathgowda1992/accounts:2.0.0" # Specify the image name for accounts
    container_name: accounts-service  # Provide the container name to avoid random name generation
    ports:
      - "8080:8080"  # Expose the port of container to outside by port mapping
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - network-routes  # Create a network communication for internal communication between services

  loans:
    image: "manjunathgowda1992/loans:2.0.0" # Specify the image name for loans
    container_name: loans-service # Provide the container name to avoid random name generation
    ports:
      - "8070:8070"    # Expose the port of container to outside by port mapping
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - network-routes

  cards:
    image: "manjunathgowda1992/cards:2.0.0" # Specify the image name for cards
    container_name: cards-service  # Provide the container name to avoid random name generation
    ports:
      - "8090:8090"  # Expose the port of container to outside by port mapping
    deploy:
      resources:
        limits:
          memory: 700m #Restricting the memory usage of container to 700MB
    networks:
      - network-routes

# Define the network communication routes
networks:
  network-routes:
    driver: "bridge"