spring:
  application:
    name: gateway-server
  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false
              lower-case-service-id: true
          httpclient:
            connect-timeout: 1000
            response-timeout: 2s

server:
  port: 9100


management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
  endpoint:
    gateway:
      access: UNRESTRICTED
info:
  app:
    name: "Gateway-server"
    description: "Gateway server application"
    version: "1.0.0"

logging:
  level:
    org:
      fourstack:
        gatewayserver: debug

resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 10
        permitted-number-of-calls-in-half-open-state: 2
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10000