spring:
  application:
    name: gateway-server
  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false
              lower-case-service-id: true

server:
  port: 9100


management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
  endpoint:
    gateway:
      access: UNRESTRICTED
info:
  app:
    name: "Gateway-server"
    description: "Gateway server application"
    version: "1.0.0"