spring:
  application:
    name: cards
  config:
    import:
      - "optional:configserver:http://localhost:8071/"
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "fourstack"
    password: "stack4@2808"

  datasource:
    url: jdbc:postgresql://postgres-aws.cz8a0smi84bm.ap-south-1.rds.amazonaws.com:5432/cards
    driver-class-name: org.postgresql.Driver
    username: postgres_aws
    password: 'B$56lueMo789nk!'
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8090
  servlet:
    context-path: /cards-service


app:
  details:
    name: cards-service
    author: Manjunath
    description: Cards Application
    version: "2.0.0"
    environment: "DEFAULT"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      access: UNRESTRICTED
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

# Add arbitrary properties to display the application info on /actuator/env
info:
  app:
    name: "cards"
    description: "Cards Application service"
    version: "1.0.0"

# Add Eureka discovery related properties
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  pattern:
    level: "%5p[${spring.application.name},%X{trace_id},%X{span_id}]"