spring:
  application:
    name: bank-config-server
  # provide the active profile as native
  profiles:
    active: native
  # Add cloud config server search locations
  cloud:
    config:
      server:
        native:
          search-locations: "file:///Users//manjunath_hm//code//cloud-config-server-files//bank-app"

server:
  port: 8071
