spring:
  application:
    name: accounts
  config:
    import:
      - "optional:configserver:http://localhost:8071/"
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "fourstack"
    password: "stack4@2808"
  datasource:
    url: jdbc:postgresql://postgres-aws.cz8a0smi84bm.ap-south-1.rds.amazonaws.com:5432/accounts
    driver-class-name: org.postgresql.Driver
    username: postgres_aws
    password: 'B$56lueMo789nk!'
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080
  servlet:
    context-path: /accounts-service

app:
  details:
    name: accounts-service
    author: Manjunath
    description: Accounts Application
    version: "2.0.0"
    environment: "DEFAULT"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      access: UNRESTRICTED
  info:
    env:
      enabled: true

# These are arbitrary properties
info:
  app:
    name: "accounts"
    description: "Accounts Application service"
    version: "1.0.0"

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
