name: banking-services
services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: banking-config-mq
    container_name: banking-rabbit-mq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    environment:
      RABBITMQ_DEFAULT_USER: "rabbit_prod"
      RABBITMQ_DEFAULT_PASS: "r@bbItProd!0109"
    extends:
      file: common-config.yml
      service: network-deploy-service

  banking-config-server:
    image: "manjunathgowda1992/banking-config-server:5.0.0" # Specify the image for config-server
    container_name: banking-config-server # Provide container name to avoid random name generation
    ports:
      - "8071:8071"  # Expose the port of container to outside by port mapping
    depends_on:
      rabbitmq:
        condition: service_healthy
    healthcheck: # To perform the health check of the container
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s  # mention after how much time of container start the curl need to be executed
    environment:  # Environment properties
      SPRING_APPLICATION_NAME: "bank-config-server"
    extends:
      file: common-config.yml
      service: microservice-base-config

  accounts:
    image: "manjunathgowda1992/accounts:5.0.0" # Specify the image name for accounts
    container_name: accounts-service  # Provide the container name to avoid random name generation
    ports:
      - "8080:8080"  # Expose the port of container to outside by port mapping
    depends_on:
      banking-config-server:
        condition: service_healthy # mention the accounts service to wait till config server is completely up and running
    environment:
      SPRING_APPLICATION_NAME: "accounts"
    extends:
      file: common-config.yml
      service: config-server-config

  loans:
    image: "manjunathgowda1992/loans:5.0.0" # Specify the image name for loans
    container_name: loans-service # Provide the container name to avoid random name generation
    ports:
      - "9000:9000"    # Expose the port of container to outside by port mapping
    depends_on:
      banking-config-server:
        condition: service_healthy # mention the loans service to wait till config server is completely up and running
    environment:
      SPRING_APPLICATION_NAME: "loans"
    extends:
      file: common-config.yml
      service: config-server-config

  cards:
    image: "manjunathgowda1992/cards:5.0.0" # Specify the image name for cards
    container_name: cards-service  # Provide the container name to avoid random name generation
    ports:
      - "8090:8090"  # Expose the port of container to outside by port mapping
    depends_on:
      banking-config-server:
        condition: service_healthy # mention the cards service to wait till config server is completely up and running
    environment:
      SPRING_APPLICATION_NAME: "cards"
    extends:
      file: common-config.yml
      service: config-server-config

# Define the network communication routes
networks:
  app-routes:
    driver: "bridge"