app:
  details:
    name: loans-service
    author: Manjunath
    description: Loans Application - Config Server PROD
    version: "2.0.0"
    environment: "PROD"

loans:
  message: "Welcome to Loans service - Config Server PROD"
  contactDetails:
    name: "John"
    # Encrypted value (Encrypted using the config server /encrypt
    email: "{cipher}6f10fc34b9cf77320a1faeff3d86387cebf020df37483769b1d9f6e5625ef1b0b87e45e72fba243188f72f20cd92a1da"
  onCallSupport:
    - (001)555-5621
    - (001)555-5623
