spring:
  application:
    name: loans
  config:
    import:
      - "optional:configserver:http://localhost:8071/"
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "fourstack"
    password: "stack4@2808"

  datasource:
    url: jdbc:postgresql://postgres-aws.cz8a0smi84bm.ap-south-1.rds.amazonaws.com:5432/loans
    driver-class-name: org.postgresql.Driver
    username: postgres_aws
    password: 'B$56lueMo789nk!'
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 9000
  servlet:
    context-path: /loans-service

app:
  details:
    name: loans-service
    author: Manjunath
    description: Loans Application
    version: "2.0.0"
    environment: "DEFAULT"

loans:
  message: "Welcome to Loans service"
  contactDetails:
    name: "Manjunath"
    email: "man1234@gmail.com"
  onCallSupport:
    - (001)111-1234
    - (001)111-1235

management:
  endpoints:
    web:
      exposure:
        include:
          - "busrefresh"
